name = "ActionsTestPackage"
uuid = "fcc2991f-48ff-5696-9cca-2d2ca3f93faf"
authors = ["Sascha Mann <git@mail.saschamann.eu>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
